config/routes.rb
Rails.application.routes.draw do
  resources :zones
  resources :areas
  root 'beacons#index'

  resources :beacons
  resources :companies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  enum state: { disabled: 0, enabled: 1 }

  has_many :zones
  belongs_to :company
end

app/models/beacon.rb
class Beacon < ApplicationRecord
  enum state: { disabled: 0, enabled: 1 }

  belongs_to :company
  belongs_to :area
  belongs_to :zone
end

app/models/company.rb
class Company < ApplicationRecord
  enum state: { disabled: 0, enabled: 1 }

  has_many :beacons
  has_many :areas
end

app/models/zone.rb
class Zone < ApplicationRecord
  enum state: { disabled: 0, enabled: 1 }

  belongs_to :area
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :notice, :alert
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:state, :name, :company_id)
    end
end

app/controllers/beacons_controller.rb
class BeaconsController < ApplicationController
  def index
    @beacons = Beacon.all
  end

  def show
    set_beacon
  end

  def new
    @beacon = Beacon.new
  end

  def edit
    set_beacon
  end

  def create
    @beacon = Beacon.new(beacon_params)

    if @beacon.save
      redirect_to @beacon, notice: 'Beacon was successfully created.'
    else
      render :new
    end
  end

  def update
    set_beacon

    if @beacon.update(beacon_params)
      redirect_to @beacon, notice: 'Beacon was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    set_beacon
    @beacon.destroy

    redirect_to beacons_url, notice: 'Beacon was successfully destroyed.'
  end

  private
  def set_beacon
    @beacon = Beacon.find(params[:id])
  end

  def beacon_params
    params.require(:beacon).permit(:state, :uniq_number, :description, :company_id, :area_id, :zone_id)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    @companies = Company.all
  end

  def show
    set_company
  end

  def new
    @company = Company.new
  end

  def edit
    set_company
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render :new
    end
  end

  def update
    set_company
    if @company.update(company_params)
      redirect_to @company, notice: 'Company was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    set_company
    @company.destroy

    redirect_to companies_url, notice: 'Company was successfully destroyed.'
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:state, :name)
  end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :set_zone, only: [:show, :edit, :update, :destroy]

  # GET /zones
  # GET /zones.json
  def index
    @zones = Zone.all
  end

  # GET /zones/1
  # GET /zones/1.json
  def show
  end

  # GET /zones/new
  def new
    @zone = Zone.new
  end

  # GET /zones/1/edit
  def edit
  end

  # POST /zones
  # POST /zones.json
  def create
    @zone = Zone.new(zone_params)

    respond_to do |format|
      if @zone.save
        format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
        format.json { render :show, status: :created, location: @zone }
      else
        format.html { render :new }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1
  # PATCH/PUT /zones/1.json
  def update
    respond_to do |format|
      if @zone.update(zone_params)
        format.html { redirect_to @zone, notice: 'Zone was successfully updated.' }
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy
    @zone.destroy
    respond_to do |format|
      format.html { redirect_to zones_url, notice: 'Zone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zone_params
      params.require(:zone).permit(:state, :name, :company_id, :zone_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/areas/_form.html.erb
<%= form_for(area) do |f| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state %>
    <%= f.number_field :state %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :company_id %>
    <%= f.number_field :company_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Areas</h1>

<table>
  <thead>
    <tr>
      <th>State</th>
      <th>Name</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.state %></td>
        <td><%= area.name %></td>
        <td><%= area.company_id %></td>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @area.state %>
</p>

<p>
  <strong>Name:</strong>
  <%= @area.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @area.company_id %>
</p>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>

app/views/beacons/_form.html.erb
<%= form_for(beacon) do |f| %>
  <% if beacon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beacon.errors.count, "error") %> prohibited this beacon from being saved:</h2>

      <ul>
      <% beacon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state %>
    <%= f.number_field :state %>
  </div>

  <div class="field">
    <%= f.label :uniq_number %>
    <%= f.text_field :uniq_number %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :company_id %>
    <%= f.number_field :company_id %>
  </div>

  <div class="field">
    <%= f.label :area_id %>
    <%= f.number_field :area_id %>
  </div>

  <div class="field">
    <%= f.label :zone_id %>
    <%= f.number_field :zone_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beacons/edit.html.erb
<h1>Editing Beacon</h1>

<%= render 'form', beacon: @beacon %>

<%= link_to 'Show', @beacon %> |
<%= link_to 'Back', beacons_path %>

app/views/beacons/index.html.erb
<h1 class='page-header'>Beacons</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>State</th>
      <th>Uniq number</th>
      <th>Description</th>
      <th>Company</th>
      <th>Area</th>
      <th>Zone</th>
      <th colspan='3'></th>
    </tr>
  </thead>

  <tbody>
    <% @beacons.each do |beacon| %>
      <tr>
        <td><%= beacon.state %></td>
        <td><%= beacon.uniq_number %></td>
        <td><%= beacon.description %></td>
        <td><%= beacon.company.name %></td>
        <td><%= beacon.area_id %></td>
        <td><%= beacon.zone_id %></td>
        <td><%= link_to 'Show', beacon %></td>
        <td><%= link_to 'Edit', edit_beacon_path(beacon) %></td>
        <td><%= link_to 'Destroy', beacon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beacon', new_beacon_path %>

app/views/beacons/new.html.erb
<h1>New Beacon</h1>

<%= render 'form', beacon: @beacon %>

<%= link_to 'Back', beacons_path %>

app/views/beacons/show.html.erb
<p>
  <strong>State:</strong>
  <%= @beacon.state %>
</p>

<p>
  <strong>Uniq number:</strong>
  <%= @beacon.uniq_number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @beacon.description %>
</p>

<p>
  <strong>Company:</strong>
  <%= @beacon.company_id %>
</p>

<p>
  <strong>Area:</strong>
  <%= @beacon.area_id %>
</p>

<p>
  <strong>Zone:</strong>
  <%= @beacon.zone_id %>
</p>

<%= link_to 'Edit', edit_beacon_path(@beacon) %> |
<%= link_to 'Back', beacons_path %>

app/views/companies/_form.html.erb
<%= form_for(company) do |f| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state %>
    <%= f.number_field :state %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>State</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.state %></td>
        <td><%= company.name %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p>
  <strong>State:</strong>
  <%= @company.state %>
</p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/_header.html.erb
<nav class='navbar navbar-inverse navbar-fixed-top'>
  <div class='container-fluid'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#navbar' aria-expanded='false' aria-controls='navbar'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>

      <%= link_to 'Time Track', root_path, class: 'navbar-brand' %>
    </div>
    <div id='navbar' class='navbar-collapse collapse'>
      <ul class='nav navbar-nav navbar-right'>
        <li><a href='#'>Dashboard</a></li>
        <li><a href='#'>Settings</a></li>
        <li><a href='#'>Profile</a></li>
        <li><a href='#'>Help</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetrack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class='container-fluid'>
      <div class='row'>
        <div class='col-sm-3 col-md-2 sidebar'>
          <ul class='nav nav-sidebar'>
            <li class='active'><a href='#'>Overview <span class='sr-only'>(current)</span></a></li>
            <li><a href='#'>Reports</a></li>
            <li><a href='#'>Analytics</a></li>
            <li><a href='#'>Export</a></li>
          </ul>
        </div>

        <div class='col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main'>
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/zones/_form.html.erb
<%= form_for(zone) do |f| %>
  <% if zone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zone.errors.count, "error") %> prohibited this zone from being saved:</h2>

      <ul>
      <% zone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state %>
    <%= f.number_field :state %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :company_id %>
    <%= f.number_field :company_id %>
  </div>

  <div class="field">
    <%= f.label :zone_id %>
    <%= f.number_field :zone_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zones/edit.html.erb
<h1>Editing Zone</h1>

<%= render 'form', zone: @zone %>

<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>

app/views/zones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zones</h1>

<table>
  <thead>
    <tr>
      <th>State</th>
      <th>Name</th>
      <th>Company</th>
      <th>Zone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zones.each do |zone| %>
      <tr>
        <td><%= zone.state %></td>
        <td><%= zone.name %></td>
        <td><%= zone.company_id %></td>
        <td><%= zone.zone_id %></td>
        <td><%= link_to 'Show', zone %></td>
        <td><%= link_to 'Edit', edit_zone_path(zone) %></td>
        <td><%= link_to 'Destroy', zone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zone', new_zone_path %>

app/views/zones/new.html.erb
<h1>New Zone</h1>

<%= render 'form', zone: @zone %>

<%= link_to 'Back', zones_path %>

app/views/zones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @zone.state %>
</p>

<p>
  <strong>Name:</strong>
  <%= @zone.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @zone.company_id %>
</p>

<p>
  <strong>Zone:</strong>
  <%= @zone.zone_id %>
</p>

<%= link_to 'Edit', edit_zone_path(@zone) %> |
<%= link_to 'Back', zones_path %>